"""empty message

Revision ID: 1d28d9126ea3
Revises: 95acc12b6531
Create Date: 2019-12-10 18:24:24.467278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d28d9126ea3'
down_revision = '95acc12b6531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Shows', 'date',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Shows', 'date',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###
