"""empty message

Revision ID: 5a250f6ce538
Revises: 3c979b136fe0
Create Date: 2019-12-10 20:29:22.540123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a250f6ce538'
down_revision = '3c979b136fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Shows', 'date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Shows', 'date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
