"""empty message

Revision ID: 95acc12b6531
Revises: bc00cb0c3207
Create Date: 2019-12-10 16:31:37.304576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95acc12b6531'
down_revision = 'bc00cb0c3207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('date', sa.Time()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'date')
    # ### end Alembic commands ###
