"""empty message

Revision ID: ad8faec7b466
Revises: c7c84cabcf15
Create Date: 2019-12-10 20:32:45.387334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8faec7b466'
down_revision = 'c7c84cabcf15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'date')
    # ### end Alembic commands ###
