"""empty message

Revision ID: c24d4a967455
Revises: 9ee2d77a6731
Create Date: 2019-12-10 14:04:51.133102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24d4a967455'
down_revision = '9ee2d77a6731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Shows', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Shows', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
