"""empty message

Revision ID: c7c84cabcf15
Revises: 5a250f6ce538
Create Date: 2019-12-10 20:32:25.827362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c84cabcf15'
down_revision = '5a250f6ce538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
