"""empty message

Revision ID: dee5db872b88
Revises: 1d28d9126ea3
Create Date: 2019-12-10 18:25:51.635557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dee5db872b88'
down_revision = '1d28d9126ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shows', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('date', postgresql.TIME(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
